# Generated by Django 6.0.1 on 2026-01-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='classmetrics',
            options={'verbose_name': 'Class Metrics', 'verbose_name_plural': 'Class Metrics'},
        ),
        migrations.AlterModelOptions(
            name='classstudent',
            options={'verbose_name': 'Class Student', 'verbose_name_plural': 'Class Students'},
        ),
        migrations.AlterModelOptions(
            name='gameresult',
            options={'verbose_name': 'Game Result', 'verbose_name_plural': 'Game Results'},
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'verbose_name': 'Game Session', 'verbose_name_plural': 'Game Sessions'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='studentachievement',
            options={'verbose_name': 'Student Achievement', 'verbose_name_plural': 'Student Achievements'},
        ),
        migrations.AlterModelOptions(
            name='studentmetrics',
            options={'verbose_name': 'Student Metrics', 'verbose_name_plural': 'Student Metrics'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='teachermetrics',
            options={'verbose_name': 'Teacher Metrics', 'verbose_name_plural': 'Teacher Metrics'},
        ),
        migrations.AlterModelOptions(
            name='teachernote',
            options={'verbose_name': 'Teacher Note', 'verbose_name_plural': 'Teacher Notes'},
        ),
    ]
